---
# tasks file for marketplace-ami
- name: Find Marketplace versions of CentOS 7 x86_64
  community.aws.ec2_ami_info:
    region: "{{ aws_inject.region | default('us-east-1') }}"
    aws_access_key: "{{ aws_inject.aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_inject.aws_secret_key | default(omit) }}"
    filters:
      product-code: 
