---
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Builder for Security Groups to use in the access control for deployed image builders
Mappings:
  AMZNPrefixL:
    cn-northwest-1:
      CORP: pl-b5a540dc  # https://apll.tools.aws.dev/#/?query=cn-north-1
    cn-north-1:
      CORP: pl-90a045f9
    us-east-1:
      CORP: pl-60b85b09
    us-west-2:
      CORP: pl-f8a64391
    us-west-1:
      CORP: pl-a4a742cd
Resources:
  InternalPrefixList: # Allow access from Amazon CORP Networks
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: >-
        bjs partition security group
      GroupName: image-builder-bjs-base-sg
      VpcId: vpc-f9f02290
      Tags:
        - Key: "maintained_by"
          Value: davdunc
      SecurityGroupIngress:
        - CidrIp: 52.95.4.28/32
          Description: Address from the local machine
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - SourcePrefixListId: !FindInMap
            - AMZNPrefixL
            - !Ref 'AWS::Region'
            - CORP
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          Description: Corporate Network access
