---
- name: System build configurations for building
  hosts: tag_task_image_builder

  remote_user: builder
  gather_facts: true

  vars:
    ec2_architecture: x86_64

  tasks:
    - name: Create Sandbox directory
      ansible.builtin.file:
        path: ${HOME}/sandbox
        state: directory
        mode: 0750

    - name: Ensure the packages are installed
      ansible.builtin.dnf:
        name:
          - jq
          - wget
          - git
          - libguestfs-bash-completion
          - rpm-build
          - git-credential-libsecret
          - unzip
          - libguestfs-tools-c
      become: true

    - name: configure the instance to store credentials in the case that they are needed
      community.general.git_config:
        name: credential.helper
        scope: global
        value: store

    - name: configure the user email for commit management to the ansible script variable
      community.general.git_config:
        name: user.email
        scope: global
        value: davdunc@amazon.com

    - name: configure the user name for commit management to the ansible script variable
      community.general.git_config:
        name: user.name
        scope: global
        value: David Duncan

    - name: clone the centos-2-awsmp repository for use
      ansible.builtin.git:
        repo: https://github.com/Internethamster/centos-2-awsmp.git
        dest: ${HOME}/sandbox/centos-2-awsmp
        version: development

    - name: Download the awscliv2
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
        dest: ${HOME}/sandbox/
      register: awscliv2

    - name: "Unzip the awscliv2 on {{ ansible_architecture }}"
      ansible.builtin.unarchive:
        dest: ${HOME}/sandbox/
        remote_src: yes
        src: "${HOME}/sandbox/awscli-exe-linux-{{ ansible_architecture }}.zip"

    - name: "Install the AWSCLIv2"
      command: ./aws/install -i ${HOME}/lib/ -b ${HOME}/bin
      args:
        chdir: ${HOME}/sandbox
        creates: ${HOME}/bin/aws
