---
- name: Identify the AMI for CentOS
  hosts:
    localhost
  connection: local

  vars:
    stage: devel
    vpcId: vpc-beb418d5
    subnetId: subnet-bb9b99c1
    ami:
      Id: ami-0a75b786d9a7f8144
      Name: "CentOS 7.8.*"
      owner_id: "125523088429"
    arch: x86_64
    boto_profile: ansible
    aws_instance_role: jenkins-ec2-role
    aws_instance_type: m5.large
    aws_region: us-east-2
  tasks:
    
  - name: Identify the AMI for CentOS
    ec2_ami_info:
      owners: "{{ ami.owner_id }}"
      region: "{{ aws_region }}"
      filters:          
        name: "{{ ami.Name }}"
        architecture: "{{ arch }}"
      profile: "{{ boto_profile }}"
    register: centos_images

  - name: Report the images
    set_fact:
      centos_image: "{{ centos_images.images[0].image_id }}"
