---
- name: Destroy the builders for all images
  hosts: localhost
  connection: local

  gather_facts: false

  vars:
    region: us-west-2
    profile: image-builder
    iam_instance_profile: 2P-Lister
    subnet: subnet-fba35eb1
    ec2_architecture: arm64
    ec2_instance_type:
      x86_64: m6i.metal
      arm64: m6g.metal
    image_id: ami-006073918dcc6f406


  tasks:
    - name: Destroy instances for building images
      amazon.aws.ec2_instance:
        state: terminated
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        tags:
          task: image-builder
      delegate_to: localhost
    - name: Destroy instances for downloading images
      amazon.aws.ec2_instance:
        state: terminated
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        tags:
          task: image-downloader
    - name: Remove the Security Stack
      amazon.aws.cloudformation:
        stack_name: "imagebuildersg"
        state: absent
        region: "{{ region }}"
        profile: "{{ profile }}"
