---
- name: Destroy the builders for all images
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    partition: china
    region: cn-northwest-1
    profile: bjs
    aws_instance_role: Tools-Instance
    subnet: subnet-5a68b633
    aws_vpc_id: vpc-f9f02290
    ec2_architecture: arm64
    ec2_instance_type:
      x86_64: c5d.metal
      arm64: c6g.metal
    image_id:
      x86_64: ami-0167519b634ad8b03
      arm64: ami-03f679efb23042ce6


  tasks:
    - name: Destroy instances for building images
      community.aws.ec2_instance:
        state: terminated
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        tags:
          task: image-builder

    - name: Destroy instances for downloading images
      community.aws.ec2_instance:
        state: terminated
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        tags:
          task: image-downloader
    - name: Remove the Security Stack
      amazon.aws.cloudformation:
        stack_name: "imagebuildersg"
        state: absent
        region: "{{ region }}"
        profile: "{{ profile }}"

