---
- name: Deploy a builder for CentOS images
  hosts: localhost
  connection: local

  gather_facts: yes

  collections:
    - community.general
    - amazon.aws

  vars:
    partition: standard
    region: us-west-2
    profile: image-builder
    aws_instance_role: image-builder-tools-instance
    subnet: subnet-fba35eb1
    aws_vpc_id: vpc-94b6f1ec
    ec2_architecture: arm64
    ec2_instance_type:
      x86_64: m6i.metal
      arm64: m6g.metal
    image_id: ami-006073918dcc6f406


  tasks:
    - name: identify the current IP address from which this is being run
      community.general.ipify_facts:
        timeout: 20
    - name: Use this address in the security group configuration
      ansible.builtin.template:
        src: "groups_{{ partition }}.j2"
        dest: "files/groups_{{ partition }}.yml"
    - name: "Define the groups_{{ partition}}.yml CFN"
      amazon.aws.cloudformation:
        stack_name: "imagebuildersg"
        region: "{{ region }}"
        profile: "{{ profile }}"
        template: "./files/groups_{{ partition }}.yml"
        create_changeset: true
        tags:
          maintained_by: "{{ ansible_user_id }}"
          Stack: image-builder

    - name: Find the CentOS Stream 9 Image in the Fedora account
      amazon.aws.ec2_ami_info:
        region: "{{ region }}"
        profile: "{{ profile }}"
        owners: 125523088429
        filters:
          architecture: "{{ ec2_architecture }}"
          name: "CentOS Stream 8*"
      register: centos_amis

    - name: Get the most recently published image
      set_fact:
        centos_ami: "{{ centos_amis.images | sort(attribute='creation_date') | last  }}"

    - name: Deploy an instance for building images
      community.aws.ec2_instance:
        name: "Builder-{{ ec2_architecture }}"
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_role: "{{ aws_instance_role }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        security_group: "image-builder-{{ partition }}-base-sg"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 20
              delete_on_termination: true
        network:
          assign_public_ip: true
        image_id: "{{ centos_ami.image_id }}"
        user_data: "{{ lookup('file', 'files/builder-instance-userdata.yml') }}"
        tags:
          task: image-builder
          maintained_by: davdunc

    - name: Deploy an instance for downloading all of the images
      community.aws.ec2_instance:
        name: "Downloader-{{ ec2_architecture }}"
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_role: "{{ aws_instance_role }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        security_group: "image-builder-{{ partition }}-base-sg"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 20
              delete_on_termination: true
        network:
          assign_public_ip: true
        image_id: "{{ centos_ami.image_id }}"
        user_data: "{{ lookup('file', 'files/builder-instance-userdata.yml') }}"
        tags:
          task: image-downloader
          maintained_by: davdunc
      when: ec2_architecture == "x86_64"
