---
- name: Deploy a builder for CentOS images in CN
  hosts: localhost
  connection: local

  gather_facts: yes

  vars:
    partition: china
    region: cn-northwest-1
    profile: bjs
    aws_instance_role: Tools-Instance
    security_group: default
    subnet: subnet-5a68b633
    aws_vpc_id: vpc-f9f02290
    ec2_architecture: arm64
    ec2_instance_type:
      x86_64: c5d.metal
      arm64: c6g.metal
    ec2_image_id:
      x86_64: ami-04fd50ab26396a163  # RHEL 8.6 Hourly
      arm64:  ami-0ce1543fea377076d  # RHEL 8.6 Hourly

  tasks:
    - name: identify the current IP address from which this is being run
      community.general.ipify_facts:
        timeout: 20
    - name: Use this address in the security group configuration
      ansible.builtin.template:
        src: "groups_{{ partition }}.j2"
        dest: "files/groups_{{ partition }}.yml"
    - name: "Define the groups_{{ partition}}.yml CFN"
      amazon.aws.cloudformation:
        stack_name: "imagebuildersg"
        region: "{{ region }}"
        profile: "{{ profile }}"
        template: "./files/groups_{{ partition }}.yml"
        create_changeset: true
        tags:
          maintained_by: "{{ ansible_user_id }}"
          Stack: image-builder

    - name: "Deploy an instance for building {{ ec2_architecture }} images."
      community.aws.ec2_instance:
        name: "Builder-{{ ec2_architecture }}"
        region: "{{ region }}"
        profile: "{{ profile }}"
        instance_role: "{{ aws_instance_role }}"
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        security_group: "image-builder-{{ partition }}-base-sg"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 20
              delete_on_termination: true
        network:
          assign_public_ip: true
        image_id: "{{ ec2_image_id[ec2_architecture] }}"
        user_data: "{{ lookup('file', 'files/builder-cn-instance-userdata.yml') }}"
        tags:
          task: image-builder
          maintained_by: davdunc

    - name: Build the EC2 instance
      amazon.aws.ec2_instance:
        name: "Downloader-{{ ec2_architecture }}"
        profile: "{{ profile }}"
        region: "{{ region }}"
        instance_role: "{{ aws_instance_role }}"
        image_id: "{{ ec2_image_id[ec2_architecture] }}"
        tags:
          task: image-downloader
          maintained_by: davdunc
        network:
          assign_public_ip: true
        vpc_subnet_id: "{{ subnet }}"
        instance_type: "{{ ec2_instance_type[ec2_architecture] }}"
        security_group: "image-builder-{{ partition }}-base-sg" 
        volumes:
           - device_name: /dev/sda1
             ebs:
               volume_size: 60
               delete_on_termination: true
        user_data: "{{ lookup('file', '../files/builder-cn-instance-userdata.yml') }}"

