--- 
- name: Build and deploy infrastructure for copying and updating the 2P Listings for OS partners
  hosts:
    localhost
  connection: local

  vars:
    stage: devel
    vpcId: vpc-beb418d5
    subnetId: subnet-bb9b99c1
    ami:
      Id: ami-0a75b786d9a7f8144
      Name: "CentOS 7.8.*"
      owner_id: "125523088429"
    arch: x86_64
    boto_profile: image-builder
    aws_instance_role: jenkins-ec2-role
    aws_instance_type: m5.large
    aws_region: us-east-2
  tasks:
    - name: centos | Identify Current Images for deployment
      community.aws.ec2_ami_info
